version: "3"

networks:
  backend:

volumes:
  pgdata:

services:
  web:
    restart: always
    build: ./web
    ports:
      - "8500:8000" # django
    depends_on:
      - postgres
    volumes:
      - ./web:/app
    networks:
      - backend
    env_file: .env
    command: ./bootup.sh

  postgres:
    restart: always
    image: postgres:10.11
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - backend

  nginx:
    restart: always
    image: nginx:1.17.8
    ports:
      - "8580:80"
    networks:
      - backend
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/dev:/etc/nginx/conf.d
