# Generated by Django 2.2.9 on 2020-02-08 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='made_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_server.Profile'),
        ),
        migrations.AddField(
            model_name='space',
            name='made_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_server.Profile'),
        ),
    ]
