# Generated by Django 2.2.9 on 2020-02-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0002_add_made_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='detailed_adresss',
            new_name='detailed_address',
        ),
    ]
