# Generated by Django 2.2.10 on 2020-02-13 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0003_rename_detailed_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('state', models.CharField(default='r', max_length=1)),
                ('participants_min', models.IntegerField(default=1)),
                ('participants_max', models.IntegerField(default=10)),
                ('required_man_class', models.CharField(default='n', max_length=1)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Program', to='django_server.Profile')),
                ('participants', models.ManyToManyField(to='django_server.Profile')),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_server.Space')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
