# Generated by Django 2.2.10 on 2020-02-15 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0005_alter_description_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_after_school',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('participants', models.ManyToManyField(to='django_server.Profile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_server.Program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
