# Generated by Django 2.2.10 on 2020-02-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0006_meeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['created_at']},
        ),
    ]
