# Generated by Django 2.2.10 on 2020-02-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0007_order_created_at_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_signin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
