# Generated by Django 2.2.10 on 2020-03-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0008_add_last_signin_and_status_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='m', max_length=1),
        ),
    ]
