# Generated by Django 2.2.10 on 2020-03-07 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0009_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='program',
            name='participants',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Meeting', to='django_server.Program'),
        ),
        migrations.CreateModel(
            name='ProgramParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProgramParticipant', to='django_server.Profile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProgramParticipant', to='django_server.Program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MeetingParticipant', to='django_server.Meeting')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MeetingParticipant', to='django_server.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
