# Generated by Django 2.2.10 on 2020-03-07 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0010_programparticipant_meetingparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='django_server.Program'),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participant', to='django_server.Meeting'),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_participant', to='django_server.Profile'),
        ),
        migrations.AlterField(
            model_name='program',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='django_server.Profile'),
        ),
        migrations.AlterField(
            model_name='programparticipant',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_participant', to='django_server.Profile'),
        ),
        migrations.AlterField(
            model_name='programparticipant',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_participant', to='django_server.Program'),
        ),
    ]
