# Generated by Django 2.2.10 on 2020-04-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0013_meeting_space'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='name',
        ),
    ]
