# Generated by Django 2.2.10 on 2020-04-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0014_remove_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(default='e', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
