# Generated by Django 2.2.13 on 2020-07-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0018_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoom',
            name='url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
