# Generated by Django 2.2.13 on 2020-07-08 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0019_change_type_url_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='zoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_server.Zoom'),
        ),
    ]
