# Generated by Django 2.2.13 on 2020-08-06 21:17

from django.db import migrations, models
import django_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0020_meeting_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image_no',
            field=models.IntegerField(default=django_server.models.get_default_no),
        ),
    ]
