# Generated by Django 2.2.13 on 2020-08-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0021_program_image_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-modified_at']},
        ),
    ]
