# Generated by Django 2.2.13 on 2021-01-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0023_order_create_at_program_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
    ]
