# Generated by Django 2.2.13 on 2021-01-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_server', '0024_program_is_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-is_notice', '-modified_at']},
        ),
    ]
