
FROM python:3.6
RUN pip install --upgrade pip
RUN pip install Django==2.2.9
RUN pip install django-extensions==2.2.6
RUN pip install django-cors-middleware==1.3.1
RUN pip install django-graph-auth==0.3.1
RUN pip install django-filter==2.2.0
RUN pip install django-prometheus==1.1.0
RUN pip install django-pandas==0.6.1
RUN pip install graphene==2.1.8
RUN pip install graphene-django==2.8.1
RUN pip install psycopg2-binary==2.8.4
RUN pip install ipython
RUN pip install tqdm

WORKDIR /app
